### ISSUE TITLE
无论搜什么category均显示domain.transform is not a function

### ISSUE THREAD

**Issue by KiriSuoh** [KIRA2ZERO/koishi-plugin-hpoi#1]
koishi desktop，koishi版本4.14.6，插件版本1.0.4

搜示例的miku那个"hpoi 一天热度 手办 -r 全年龄 -n 36 -k miku"也不行

qq回复：
参数 category 输入无效，domain.transform is not a function

koishi日志：
`i18n missing domain.transform is not a function`

**Comment by KIRA2ZERO** [comment]
我自己测试了一下还是能正常工作的，你把你发的指令和koishi日志截图发一下

**Comment by KiriSuoh** [comment]
指令
![QQ截图20230922225320](https://github.com/KIRA2ZERO/koishi-plugin-hpoi/assets/18628194/61fc8bf7-34d3-4dde-bde5-000a87f106f3)

日志
![QQ截图20230922225345](https://github.com/KIRA2ZERO/koishi-plugin-hpoi/assets/18628194/17b0877e-2461-4cd1-a051-1708df1f43c2)

**Comment by KIRA2ZERO** [comment]
已复现问题 将尽快发布下一版修复

**Comment by KIRA2ZERO** [comment]
已修复
